### ISSUE TITLE
I am not able to see files. its showing folder only. 

### ISSUE THREAD

**Issue by shalender** [dailykit/react-file-manager#5]

**Comment by prvnbist** [comment]
In the left sidebar?

**Comment by shalender** [comment]
Yes, both left side bar and center.
Also, the project doesn't runs if I try to run it as it is.
It gives this "TypeError: Cannot read property 'queryData' of undefined" type of error many places.
I have used tree-beard to make it runnable after commenting the undefined type errors.
Can you suggest what is that I am missing or share your ideas?

**Comment by prvnbist** [comment]
You are missing the data source i.e the filesystem. Currently it makes a request to the server to fetch the folders/files. I will surely update the code to prevent the errors and provide a better way to input files w/o any backend involved as a static value.

The app is WIP and needs lots of improvements, thanks for reporting this.

**Comment by shalender** [comment]
Okay, Thanks for the clarification.
